# COLMAP Pipeline Default Configuration

# General Settings
general:
  use_gpu: true
  cpu_only: false
  num_threads: -1  # -1 = auto-detect
  log_level: "INFO"
  checkpoint_resume: true

# Frame Extraction (for video input)
frame_extraction:
  fps: 2  # Extract 2 frames per second
  max_frames: 300
  quality: 95  # JPEG quality (1-100)
  resize_max_dimension: null  # null = no resize, or e.g., 1920

# Keyframe Selection
keyframe_selection:
  enabled: true
  method: "difference"  # "difference", "blur", or "both"
  difference_threshold: 25.0  # Mean pixel difference threshold
  blur_threshold: 100.0  # Variance of Laplacian threshold
  min_keyframe_interval: 5  # Minimum frames between keyframes

# COLMAP Feature Extraction
feature_extraction:
  camera_model: "OPENCV"  # SIMPLE_PINHOLE, PINHOLE, SIMPLE_RADIAL, RADIAL, OPENCV, OPENCV_FISHEYE, FULL_OPENCV
  single_camera: true
  gpu_index: "0"
  sift:
    max_num_features: 8192
    first_octave: -1  # -1 = original image resolution
    num_octaves: 4
    octave_resolution: 3
    peak_threshold: 0.0066666666667
    edge_threshold: 10
    max_num_orientations: 2
    upright: false

# COLMAP Feature Matching
feature_matching:
  method: "sequential"  # "exhaustive", "sequential", "spatial", "vocab_tree"
  sequential:
    overlap: 10  # Number of overlapping images
    quadratic_overlap: false
    loop_detection: true
    loop_detection_num_images: 50
  exhaustive:
    block_size: 50
  spatial:
    max_num_neighbors: 50
    max_distance: 0.7
  gpu_index: "0"
  cross_check: true
  max_ratio: 0.8
  max_distance: 0.7
  max_error: 4.0

# COLMAP Sparse Reconstruction (Mapper)
sparse_reconstruction:
  min_num_matches: 15
  ignore_watermarks: false
  multiple_models: false
  max_num_models: 50
  max_model_overlap: 20
  min_model_size: 10
  init_image_id1: -1
  init_image_id2: -1
  init_num_trials: 200
  extract_colors: true
  num_threads: -1
  ba_refine_focal_length: true
  ba_refine_principal_point: false
  ba_refine_extra_params: true

# Image Undistortion
undistortion:
  max_image_size: 2000  # Maximum dimension for undistorted images
  blank_pixels: 0.0
  min_scale: 0.2
  max_scale: 2.0
  roi_min_x: 0.0
  roi_min_y: 0.0
  roi_max_x: 1.0
  roi_max_y: 1.0

# Dense Reconstruction (PatchMatch Stereo)
dense_reconstruction:
  enabled: true
  window_radius: 5
  window_step: 1
  sigma_spatial: 3.0
  sigma_color: 0.2
  num_samples: 15
  ncc_sigma: 0.6
  min_triangulation_angle: 1.0
  incident_angle_sigma: 0.9
  num_iterations: 5
  geom_consistency: true
  geom_consistency_regularizer: 0.3
  geom_consistency_max_cost: 3.0
  filter: true
  filter_min_ncc: 0.1
  filter_min_triangulation_angle: 3.0
  filter_min_num_consistent: 2
  filter_geom_consistency_max_cost: 1.0
  cache_size: 32
  gpu_index: "0"
  depth_min: 0.0
  depth_max: 100.0
  write_consistency_graph: false

# Stereo Fusion
stereo_fusion:
  min_num_pixels: 5
  max_num_pixels: 10000
  max_traversal_depth: 100
  max_reproj_error: 2.0
  max_depth_error: 0.01
  max_normal_error: 10.0
  check_num_images: 50
  cache_size: 32

# Meshing (Poisson Reconstruction)
meshing:
  enabled: true
  method: "poisson"  # "poisson" or "delaunay"
  poisson:
    depth: 11  # Octree depth (higher = more detail, slower)
    trim: 7
    color: 16
  delaunay:
    max_proj_dist: 20.0
    max_depth_dist: 20.0
    visibility_sigma: 2.0
    distance_sigma_factor: 1.0
    quality_regularization: 1.0

# Texturing
texturing:
  enabled: false  # Requires external tool like texrecon
  texture_size: 4096
  tone_mapping: "gamma"

# Output Settings
output:
  sparse_format: "BIN"  # "BIN" or "TXT"
  export_ply: true
  export_obj: true
  export_texture: false
  generate_report: true

# Quality Presets (override above settings)
presets:
  fast:
    feature_extraction:
      sift:
        max_num_features: 4096
    dense_reconstruction:
      window_radius: 3
      num_iterations: 3
    meshing:
      poisson:
        depth: 9
  
  high:
    feature_extraction:
      sift:
        max_num_features: 16384
    dense_reconstruction:
      window_radius: 7
      num_iterations: 7
    meshing:
      poisson:
        depth: 13

